### ISSUE TITLE
Rapid consecutive builds of master cause release problems

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1171]
Assume `master` is pushed containing commit `A`. Another commit `B` is added on top of `master` and pushed. Assuming the build for commit `A` starts before `B` is pushed, the following occurs when CI tries to add a `publish` commit on top of `A` (but before `B`) -

```
lerna info version 2.11.0
lerna info versioning independent
lerna info Checking for updated packages...
lerna info Comparing with @d3fc/d3fc-annotation@2.0.4.
lerna info Checking for prereleased packages...

Changes:
 - @d3fc/d3fc-site: 0.0.6 => 0.0.7 (private)

lerna info auto-confirmed 
lerna info publish Publishing packages to npm...
lerna info git Pushing tags...
lerna ERR! execute caught error
lerna ERR! Error: To https://github.com/d3fc/d3fc.git
lerna ERR!  * [new tag]         @d3fc/d3fc-site@0.0.7 -> @d3fc/d3fc-site@0.0.7
lerna ERR!  ! [rejected]        master -> master (non-fast-forward)
lerna ERR! error: failed to push some refs to 'https://[secure]@github.com/d3fc/d3fc.git'
lerna ERR! hint: Updates were rejected because the tip of your current branch is behind
lerna ERR! hint: its remote counterpart. Integrate the remote changes (e.g.
lerna ERR! hint: 'git pull ...') before pushing again.
lerna ERR! hint: See the 'Note about fast-forwards' in 'git push --help' for details.
lerna ERR! 
lerna ERR!     at Function.module.exports.sync (/home/travis/build/d3fc/d3fc/node_modules/execa/index.js:303:26)
lerna ERR!     at Function.execSync (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
lerna ERR!     at Function.pushWithTags (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/GitUtilities.js:155:39)
lerna ERR!     at /home/travis/build/d3fc/d3fc/node_modules/lerna/lib/commands/PublishCommand.js:367:36
lerna ERR!     at PublishCommand.npmUpdateAsLatest (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/commands/PublishCommand.js:857:16)
lerna ERR!     at /home/travis/build/d3fc/d3fc/node_modules/lerna/lib/commands/PublishCommand.js:359:16
lerna ERR!     at /home/travis/build/d3fc/d3fc/node_modules/lerna/lib/commands/PublishCommand.js:848:9
lerna ERR!     at /home/travis/build/d3fc/d3fc/node_modules/async/lib/async.js:726:13
lerna ERR!     at /home/travis/build/d3fc/d3fc/node_modules/async/lib/async.js:52:16
```

Note that the tag is pushed before the non-FF branch change. This causes subsequent builds to fail with -

```
lerna info version 2.11.0
lerna info versioning independent
lerna info Checking for updated packages...
lerna info Comparing with @d3fc/d3fc-annotation@2.0.4.
lerna info Checking for prereleased packages...

Changes:
 - @d3fc/d3fc-annotation: 2.0.4 => 2.0.5
 - @d3fc/d3fc-brush: 2.0.4 => 2.0.5
 - @d3fc/d3fc-chart: 2.0.4 => 2.0.5
 - @d3fc/d3fc-element: 5.0.4 => 5.0.5
 - @d3fc/d3fc-random-data: 3.0.2 => 3.0.3
 - @d3fc/d3fc-series: 4.0.4 => 4.0.5
 - @d3fc/d3fc-shape: 5.0.2 => 5.0.3
 - @d3fc/d3fc-site: 0.0.6 => 0.0.7 (private)
 - @d3fc/d3fc-technical-indicator: 7.0.4 => 7.0.5
 - d3fc: 14.0.5 => 14.0.6

lerna info auto-confirmed 
lerna ERR! execute caught error
lerna ERR! Error: fatal: tag '@d3fc/d3fc-site@0.0.7' already exists
lerna ERR! 
lerna ERR!     at Function.module.exports.sync (/home/travis/build/d3fc/d3fc/node_modules/execa/index.js:303:26)
lerna ERR!     at Function.execSync (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
lerna ERR!     at Function.addTag (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/GitUtilities.js:100:39)
lerna ERR!     at /home/travis/build/d3fc/d3fc/node_modules/lerna/lib/commands/PublishCommand.js:767:39
lerna ERR!     at Array.forEach (<anonymous>)
lerna ERR!     at PublishCommand.gitCommitAndTagVersionForUpdates (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/commands/PublishCommand.js:766:12)
lerna ERR!     at PublishCommand.commitAndTagUpdates (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/commands/PublishCommand.js:738:26)
lerna ERR!     at PublishCommand.execute (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/commands/PublishCommand.js:329:14)
{ Error: fatal: tag '@d3fc/d3fc-site@0.0.7' already exists

    at Function.module.exports.sync (/home/travis/build/d3fc/d3fc/node_modules/execa/index.js:303:26)
    at Function.execSync (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
    at Function.addTag (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/GitUtilities.js:100:39)
    at /home/travis/build/d3fc/d3fc/node_modules/lerna/lib/commands/PublishCommand.js:767:39
    at Array.forEach (<anonymous>)
    at PublishCommand.gitCommitAndTagVersionForUpdates (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/commands/PublishCommand.js:766:12)
    at PublishCommand.commitAndTagUpdates (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/commands/PublishCommand.js:738:26)
    at PublishCommand.execute (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/commands/PublishCommand.js:329:14)
    at PublishCommand._attempt (/home/travis/build/d3fc/d3fc/node_modules/lerna/lib/Command.js:377:21)
    at /home/travis/build/d3fc/d3fc/node_modules/lerna/lib/Command.js:364:16 exitCode: 1 }
```

**Comment by chrisprice** [comment]
We can work around this temporarily by removing any invalid tags (i.e. tags that reference commits that don't exist in `master`) and not building too quickly but it isn't ideal...
