### ISSUE TITLE
Load d3fc as es module

### ISSUE THREAD

**Issue by kossidts** [d3fc/d3fc#1715]
Is there any easy way to import this npm package as es-module?  I set `"type": "module"` to my  `package.json` file and 
`import * as fc from 'd3fc'` is not working...

**Comment by chrisprice** [comment]
Seems to work for me. https://codesandbox.io/embed/broken-thunder-066kz?codemirror=1

Can you reproduce on code sandbox or equivalent to allow us to debug?

**Comment by kossidts** [comment]
Thanks for the quick replay.
Since I'm not very familiar with codesandbox.io, I couldn't run the npm scripts directly. 

For a clean reproduction: 
- Create a new blank directory and change into it: `mkdir chart && cd chart`
- Initialise the directory as an npm project: `npm init -y`
- Add `"type": "module",` to the package.json file
- Install the necessary  packages: `npm i d3 d3fc`
- Create an `index.js` file with the following content: 
```
import * as d3 from "d3";
import * as fc from "d3fc";
```
- Open a terminal and change to the chart directory
- Run node index.js

 
I am getting
```sh
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_REQUIRE_ESM]: ....
```

I even upgraded to the latest versions:
npm v7.24.0
node v16.10.0

**Comment by chrisprice** [comment]
Exact error from reproduction steps above - 
```sh
$ node index.js 
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /.../chart/node_modules/d3-array/src/index.js
require() of ES modules is not supported.
require() of /.../chart/node_modules/d3-array/src/index.js from /.../chart/node_modules/d3fc/build/d3fc.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /.../chart/node_modules/d3-array/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /.../chart/node_modules/d3fc/build/d3fc.js:2:85
    at Object.<anonymous> (/.../chart/node_modules/d3fc/build/d3fc.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by kossidts** [comment]
Correct...  And since renaming files of external libraries is not an option, is it possible for d3fc to provide a hibrid/conditional export (https://2ality.com/2019/10/hybrid-npm-packages.html)?

**Comment by chrisprice** [comment]
Sorry was making notes to myself. I quickly tried applying the following config to each package -

```js
{
  // ...
  "type": "module",
  "main": "build/d3fc-extent.js",
  "exports": {
    "import": "./index.js",
    "require": "./build/d3fc-extent.js"
  },
  "module": "index",
  // ...
}
  ```

The problem is then that our relative imports don't have .js extensions. I don't see a problem with adding them but that would require some regex wizardry following by testing of the various builds/tests to make sure nothing is broken.

**Comment by romaleev** [comment]
Also have this issue and unable to run this package within Node.js, please fix if possible

**Comment by romaleev** [comment]
Solved by manually changing package.json "type": "module" and adding file extensions

**Comment by parth-choudhary** [comment]
@romaleev can please explain which package.json and which file extensions are needed to be changed?

**Comment by romaleev** [comment]
> @romaleev can please explain which package.json and which file extensions are needed to be changed?

I use d3fc/d3fc-technical-indicator,
So in d3fc/d3fc-technical-indicator/package.json added "type": "module".
And added the relative import file extension within every file inside.
Example `d3fc-technical-indicator/src/bollingerBands.js`:
```
import { mean, deviation } from 'd3-array';
import { rebind } from '@d3fc/d3fc-rebind';
import _slidingWindow from './slidingWindow.js'; // <-
import { convertNaN } from './fn.js'; // <-
...
```

**Comment by TakodaS** [comment]
I solved this exact issue by creating aliases for the d3fs modules:

```ts
// tsconfig.ts
 "paths" : {
    "@d3fc/*": [ "./node_modules/@d3fc/*" ]
 },
...

//vite.config
import path from "path"

resolve.alias:  { '@d3fc': path.resolve(__dirname,'./node_modules/@d3fc')}
```

This way, instead of trying to include the d3fc umd bundle, the source code is directly imported and built into my esmodule without needing to be modified!
